name: mycompass_admin_website
description: "A mycompass_admin_website."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  google_fonts: ^6.2.1
  charts_flutter_new: ^0.12.0
  data_table_2: ^2.5.16
  flutter_svg: ^2.0.16
  provider: ^6.1.2
  fl_chart: ^0.69.2
  iconsax: ^0.0.8
  page_transition: ^2.1.0
  dynamic_path_url_strategy: ^1.0.0
  file_picker: ^8.1.7
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

